### ISSUE TITLE
Seems to get stuck during initial install.

### ISSUE THREAD

**Issue by stuntrocket** [tjventurini/modxvm#11]
Running **vagrant up** on **Mac OS Sierra**.  Seems to crash when setting up network interfaces, after asking for SSH password.

==> modxvm: Waiting for machine to boot. This may take a few minutes...
    modxvm: SSH address: 127.0.0.1:2222
    modxvm: SSH username: ubuntu
    modxvm: SSH auth method: password
ubuntu
==> modxvm: Machine booted and ready!
==> modxvm: Checking for guest additions in VM...
==> modxvm: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifdown eth1 2> /dev/null

Stdout from the command:

Stderr from the command:
mesg: ttyname failed: Inappropriate ioctl for device

**Comment by tjventurini** [comment]
Please update your vagrant boxes and try again.

**Comment by tjventurini** [comment]
Had a similar problem on Windows. The solution was simple. Set the following in the Vagrant file to show up the gui when vagrant start.

```
config.vm.provider "virtualbox" do |vb|
    vb.gui = true;
end
```

Then, if the system needs some input on bootup, give it ;)
If there is another error, pls report it.

**Comment by stuntrocket** [comment]
Thank you. I didn't actually know you could do that, haha!

**Comment by stuntrocket** [comment]
Hi, 

That does seem to open up the GUI, but it still asks for a login user and password for ubuntu-xenial?
I tried a few combinations using 'ubuntu' but no luck.

Thanks
Danny

**Comment by tjventurini** [comment]
Nice, so now we know that it gets stuck on the login. Usualy I could fix this issue on other vagrant setups by increasing the ssh timezone in the Vagrantfile. Pls try out the following.

`config.vm.boot_timeout 1200`

Default value is 300. With 1200 I usualy get through ;)

Ref.: https://www.vagrantup.com/docs/vagrantfile/machine_settings.html

PS: You don't have to login manually, eaven if you open the gui - Vagrant will handle that for you.

**Comment by tjventurini** [comment]
@stuntrocket were u able to fix it?
